// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2dkTbotBYFQEQYCoM_GYsPzkP9JHNu8',
    appId: '1:757029850351:android:79e162fdf99935a396df1a',
    messagingSenderId: '757029850351',
    projectId: 'chatverse-fdbe8',
    storageBucket: 'chatverse-fdbe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAULXCIBXmk0jR3p4kYqz4EyyijD1I0quA',
    appId: '1:757029850351:ios:e3dada57bc6bf47896df1a',
    messagingSenderId: '757029850351',
    projectId: 'chatverse-fdbe8',
    storageBucket: 'chatverse-fdbe8.appspot.com',
    androidClientId: '757029850351-6lk2q47p3k15b2jdf4jefg168dujv72k.apps.googleusercontent.com',
    iosClientId: '757029850351-uqgnqqviqprbisvpst1k3g8g9eabd8h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatVerse',
  );
}
